### PR TITLE
Add support for including environment variables in config files using Go template

### PR DESCRIPTION
**Pull request by cjcormack**

### CODE REVIEW

**Comment by dombenson** [comment]
I like the feature, both as a generic way of supporting environment-supplied data and for how it makes explicit where a given setting is sourced - but I don't like that it changes the meaning of existing files. I appreciate that the fallback to keeping the literal template string offsets that in most practical cases.
I am considering whether I would prefer to use an alternative to `=` to indicate environment assignments, e.g:
```
[foo]
bar ENV example_foo_bar
```
- this doesn't have any ambiguity as that setting would currently be a parse error. It also means that any other client reading the same file would not misinterpret it as a literal string.
- I have not been able to find any common methods for referencing the environment in ini-style files, so I don't have an existing implementation in mind to preserve compatibility.
- With that said, PHP `parse_ini_string` for example will ignore such a line, which seems like the closest-to-correct behaviour for interoperation.
- The template system potentially makes a bunch of features doable, but it is also somewhat unnecessarily complex and for a user likely to increase expectations of supported methods. That they would fall through to the literal string feels surprising to such a user, especially as it is a runtime rather than parse-time error.

**Comment by cjcormack** [comment]
> but I don't like that it changes the meaning of existing files.

I don't disagree, which is why I made the feature opt-in with the need to call `ini.ParseEnvironmentVariables()`.

> I am considering whether I would prefer to use an alternative to `=` to indicate environment assignments

My concern with this is how it interacts with other INI parsers. While the Go template format isn't particularly friendly format for other languages, we could potentially add support for them in application code (without the need to modify a library)—e.g. in PHP parsing the value if it has come in from `parse_ini_string`, however, if the value is ignored it wouldn't be possible to do that.

**Comment by cjcormack** [comment]
I have change the approach to one that avoids the need to specify in the base config each environment variable and makes it an override of the config value (rather than the value having to come from the environment).

**Comment by dombenson** [comment]
OK, I think I like this more. The `EnableEnvironmentVariableOverrides` is simple and explicit, and has no interactions with other users of the config file.

**Pull request merged**
